sudo: required
services: 
  - docker

before_install:
  - docker build -t tusharbecoding/docker-react -f Dockerfile.dev .

script:
  - docker run tusharbecoding/docker-react npm run test -- --coverage